//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp_Car
{
    using System;
    using System.Collections.Generic;
    
    public partial class Body
    {
        public int Body_id { get; set; }
        public string BodyType { get; set; }
        public string Doors { get; set; }
    }
}
