//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp_Car
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main
    {
        public int Car_id { get; set; }
        public Nullable<int> Engine_id { get; set; }
        public string Color { get; set; }
        public string Name { get; set; }
        public string Make { get; set; }
        public string Year { get; set; }
    
        public virtual Engine Engine { get; set; }
    }
}
